### ISSUE TITLE
IDs für neue Cards im Backend generieren

### ISSUE THREAD

**Issue by Aaretaler** [Aaretaler/web_project#25]
IDs für neue Cards im Backend generieren, wenn möglich.

**Comment by Aaretaler** [comment]
(DONE)
Frage an Tobi: dann muss nach jedem post ein neues get gemacht werden, um die neue ID auch im app state zu haben?
Das war ja nicht der Sinn von "möglichst wenig API calls"...

**Comment by Quatschkopf1991** [comment]
Im post zurück schicken
