### ISSUE TITLE
post() und fetch() direkt exportieren

### ISSUE THREAD

**Issue by Aaretaler** [Aaretaler/web_project#26]
ServerAPI.ts: Gibt hier keinen Grund um Klassen zu verwenden. Einfach post() und fetch() direkt exportieren oder in ein Objekt packen.

**Comment by Quatschkopf1991** [comment]
Done.  post() und fetch() direkt exportiert

**Comment by Aaretaler** [comment]
fixed in cbfbb0f0092f3f18e99f8a3587bb8cc4ff93cb3d
