### ISSUE TITLE
ServerAPI.ts: then-Method-Chaining anstatt async/await verwendet.

### ISSUE THREAD

**Issue by Aaretaler** [Aaretaler/web_project#29]
ServerAPI.ts: then-Method-Chaining anstatt async/await verwendet.

**Comment by Quatschkopf1991** [comment]
Meiner Meinung nach bereits umgesetzt in der ServerAPI.ts.  Kein async/await verwendet.

**Comment by Quatschkopf1991** [comment]
auf async/await vwerenden

**Comment by Aaretaler** [comment]
Fixed in e12e96dcb422a4c5d39b24ecb4bf25ad35a06b5c

**Comment by Aaretaler** [comment]
Closed in #66
