### ISSUE TITLE
Context.tsx: Doppeltes Rendering vom <React.StrictMode /> 

### ISSUE THREAD

**Issue by Aaretaler** [Aaretaler/web_project#33]
Context.tsx: Doppeltes Rendering vom <React.StrictMode /> sauber gelöst mit dem AbortController.

=> ist das positives feedback? => Implementierungn prüfen!

**Comment by Aaretaler** [comment]
Tobi fragen??
@Blizzer92  @Quatschkopf1991 
Wie versteht ihr das?

**Comment by Quatschkopf1991** [comment]
ist positiv gemeint :-)
