### ISSUE TITLE
GamePage.tsx:14: Linter-Errors beachten

### ISSUE THREAD

**Issue by Aaretaler** [Aaretaler/web_project#36]
GamePage.tsx:14: Linter-Errors beachten: mit “const” anstatt “let” deklarieren. Häufig bei useState() gesehen.

- [x] Linter setup => gleiches Setup wie Tobi verwenden
- [x] "const" findings in ganzem Code fixen
- [x] weitere findings fixen
- [x] Team informieren wie linter eingerichtet werden kann
- [x] Einheitliche verwendung von ";" in ganzem code prüfen (nehme an linther macht das auch)

**Comment by Aaretaler** [comment]
linter rules sind im file .eslintrc.cjs.

=> In Unterlagen nachschauen wie dieser linter benutzt werden kann und unseren code mit diesen Linterrules prüfen

**Comment by Blizzer92** [comment]
Bei mir gibt es im Context Menü vom Projekt den Punkt Fix EsLintErrors.

![grafik](https://github.com/user-attachments/assets/cbbcd3e0-8627-4684-99be-5ff59b5bd213)
