### ISSUE TITLE
cardEditor.tsx:23: Verschachtelungen (indents) mittels Guards verringern

### ISSUE THREAD

**Issue by Aaretaler** [Aaretaler/web_project#39]
cardEditor.tsx:23: Verschachtelungen (indents) mittels Guards verringern: if(!card) return

**Comment by Aaretaler** [comment]
Frage an Tobi:
Was genau gewinnen wir hier? ich sehe den Sinn nicht.

**Comment by Quatschkopf1991** [comment]
macht den code lesbarer. Generell gutes Pattern.
