### ISSUE TITLE
UI: Fix responsive design issues

### ISSUE THREAD

**Issue by Aaretaler** [Aaretaler/web_project#62]
- [x] Game result: "Title card" einfärben
- [x] Header-refactoring im Desktopformat
- [x] User in Header anzeigen
- [x] Manage Cards page: Raster im Desktopformat verschoben
- [x] Refine layout login page in Desktopformat
- [x] Nach login auf / navigieren

**Comment by Quatschkopf1991** [comment]
Done

**Comment by Quatschkopf1991** [comment]
fixed all points
